#translator.py
"""
Handles language mapping and translation utilities for the Telegram translation bot.
Enable users to select languages by name and display translations in a clear, readable format.

Functions:
- validate_language(): Validates user input and returns language code.
- translate_to_multiple_languages(): Translates a message to multiple languages using Google Translator.
"""

from deep_translator import GoogleTranslator

# Language code to language name mapping
LANGUAGE_NAMES = {
    "af": "Afrikaans",
    "sq": "Albanian (Shqip)",
    "am": "Amharic (አማርኛ)",
    "ar": "Arabic (العربية)",
    "hy": "Armenian (Հայերեն)",
    "as": "Assamese (অসমীয়া)",
    "ay": "Aymara (Aymar aru)",
    "az": "Azerbaijani (Azərbaycanca)",
    "bm": "Bambara (Bamanankan)",
    "eu": "Basque (Euskara)",
    "be": "Belarusian (Беларуская)",
    "bn": "Bengali (বাংলা)",
    "bho": "Bhojpuri (भोजपुरी)",
    "bs": "Bosnian (Bosanski)",
    "bg": "Bulgarian (Български)",
    "ca": "Catalan (Català)",
    "ceb": "Cebuano (Cebuano)",
    "ny": "Chichewa (ChiCheŵa)",
    "zh-CN": "Chinese Simplified (简体中文)",
    "zh-TW": "Chinese Traditional (繁體中文)",
    "co": "Corsican (Corsu)",
    "hr": "Croatian (Hrvatski)",
    "cs": "Czech (Čeština)",
    "da": "Danish (Dansk)",
    "dv": "Dhivehi (ދިވެހި)",
    "doi": "Dogri (डोगरी)",
    "nl": "Dutch (Nederlands)",
    "en": "English",
    "eo": "Esperanto (Esperanto)",
    "et": "Estonian (Eesti)",
    "ee": "Ewe (Eʋegbe)",
    "tl": "Filipino (Filipino)",
    "fi": "Finnish (Suomi)",
    "fr": "French (Français)",
    "fy": "Frisian (Frysk)",
    "gl": "Galician (Galego)",
    "ka": "Georgian (ქართული)",
    "de": "German (Deutsch)",
    "el": "Greek (Ελληνικά)",
    "gn": "Guarani (Avañe'ẽ)",
    "gu": "Gujarati (ગુજરાતી)",
    "ht": "Haitian Creole (Kreyòl Ayisyen)",
    "ha": "Hausa (Hausa)",
    "haw": "Hawaiian (ʻŌlelo Hawaiʻi)",
    "iw": "Hebrew (עברית)",
    "hi": "Hindi (हिन्दी)",
    "hmn": "Hmong (Hmoob)",
    "hu": "Hungarian (Magyar)",
    "is": "Icelandic (Íslenska)",
    "ig": "Igbo (Asụsụ Igbo)",
    "ilo": "Ilocano (Ilokano)",
    "id": "Indonesian (Bahasa Indonesia)",
    "ga": "Irish (Gaeilge)",
    "it": "Italian (Italiano)",
    "ja": "Japanese (日本語)",
    "jw": "Javanese (Basa Jawa)",
    "kn": "Kannada (ಕನ್ನಡ)",
    "kk": "Kazakh (Қазақ тілі)",
    "km": "Khmer (ភាសាខ្មែរ)",
    "rw": "Kinyarwanda (Ikinyarwanda)",
    "gom": "Konkani (कोंकणी)",
    "ko": "Korean (한국어)",
    "kri": "Krio (Krio)",
    "ku": "Kurdish Kurmanji (Kurmancî)",
    "ckb": "Kurdish Sorani (کوردیی سۆرانی)",
    "ky": "Kyrgyz (Кыргызча)",
    "lo": "Lao (ລາວ)",
    "la": "Latin (Latina)",
    "lv": "Latvian (Latviešu)",
    "ln": "Lingala (Lingála)",
    "lt": "Lithuanian (Lietuvių)",
    "lg": "Luganda (Luganda)",
    "lb": "Luxembourgish (Lëtzebuergesch)",
    "mk": "Macedonian (Македонски)",
    "mai": "Maithili (मैथिली)",
    "mg": "Malagasy (Malagasy)",
    "ms": "Malay (Bahasa Melayu)",
    "ml": "Malayalam (മലയാളം)",
    "mt": "Maltese (Malti)",
    "mi": "Maori (Te Reo Māori)",
    "mr": "Marathi (मराठी)",
    "mni-Mtei": "Meiteilon (Manipuri) (ꯃꯤꯇꯩꯂꯣꯟ)",
    "lus": "Mizo (Mizo ṭawng)",
    "mn": "Mongolian (Монгол)",
    "my": "Myanmar (Burmese) (မြန်မာစာ)",
    "ne": "Nepali (नेपाली)",
    "no": "Norwegian (Norsk)",
    "or": "Odia (Oriya) (ଓଡ଼ିଆ)",
    "om": "Oromo (Afaan Oromoo)",
    "ps": "Pashto (پښتو)",
    "fa": "Persian (فارسی)",
    "pl": "Polish (Polski)",
    "pt": "Portuguese (Português)",
    "pa": "Punjabi (ਪੰਜਾਬੀ)",
    "qu": "Quechua (Runasimi)",
    "ro": "Romanian (Română)",
    "ru": "Russian (Русский)",
    "sm": "Samoan (Gagana Sāmoa)",
    "sa": "Sanskrit (संस्कृतम्)",
    "gd": "Scots Gaelic (Gàidhlig)",
    "nso": "Sepedi (Sesotho sa Leboa)",
    "sr": "Serbian (Српски)",
    "st": "Sesotho (Sesotho)",
    "sn": "Shona (chiShona)",
    "sd": "Sindhi (سنڌي)",
    "si": "Sinhala (සිංහල)",
    "sk": "Slovak (Slovenčina)",
    "sl": "Slovenian (Slovenščina)",
    "so": "Somali (Soomaaliga)",
    "es": "Spanish (Español)",
    "su": "Sundanese (Basa Sunda)",
    "sw": "Swahili (Kiswahili)",
    "sv": "Swedish (Svenska)",
    "tg": "Tajik (Тоҷикӣ)",
    "ta": "Tamil (தமிழ்)",
    "tt": "Tatar (Татарча)",
    "te": "Telugu (తెలుగు)",
    "th": "Thai (ไทย)",
    "ti": "Tigrinya (ትግርኛ)",
    "ts": "Tsonga (Xitsonga)",
    "tr": "Turkish (Türkçe)",
    "tk": "Turkmen (Türkmençe)",
    "ak": "Twi (Twi)",
    "uk": "Ukrainian (Українська)",
    "ur": "Urdu (اردو)",
    "ug": "Uyghur (ئۇيغۇرچە)",
    "uz": "Uzbek (Oʻzbekcha)",
    "vi": "Vietnamese (Tiếng Việt)",
    "cy": "Welsh (Cymraeg)",
    "xh": "Xhosa (isiXhosa)",
    "yi": "Yiddish (ייִדיש)",
    "yo": "Yoruba (Yorùbá)",
    "zu": "Zulu (isiZulu)",
}

LANGUAGE_CODES = {
    'afrikaans': 'af',
    'albanian': 'sq',
    'amharic': 'am',
    'arabic': 'ar',
    'armenian': 'hy',
    'assamese': 'as',
    'aymara': 'ay',
    'azerbaijani': 'az',
    'bambara': 'bm',
    'basque': 'eu',
    'belarusian': 'be',
    'bengali': 'bn',
    'bhojpuri': 'bho',
    'bosnian': 'bs',
    'bulgarian': 'bg',
    'catalan': 'ca',
    'cebuano': 'ceb',
    'chichewa': 'ny',
    'chinese simplified': 'zh-CN',
    'chinese traditional': 'zh-TW',
    'corsican': 'co',
    'croatian': 'hr',
    'czech': 'cs',
    'danish': 'da',
    'dhivehi': 'dv',
    'dogri': 'doi',
    'dutch': 'nl',
    'english': 'en',
    'esperanto': 'eo',
    'estonian': 'et',
    'ewe': 'ee',
    'filipino': 'tl',
    'finnish': 'fi',
    'french': 'fr',
    'frisian': 'fy',
    'galician': 'gl',
    'georgian': 'ka',
    'german': 'de',
    'greek': 'el',
    'guarani': 'gn',
    'gujarati': 'gu',
    'haitian creole': 'ht',
    'hausa': 'ha',
    'hawaiian': 'haw',
    'hebrew': 'iw',
    'hindi': 'hi',
    'hmong': 'hmn',
    'hungarian': 'hu',
    'icelandic': 'is',
    'igbo': 'ig',
    'ilocano': 'ilo',
    'indonesian': 'id',
    'irish': 'ga',
    'italian': 'it',
    'japanese': 'ja',
    'javanese': 'jw',
    'kannada': 'kn',
    'kazakh': 'kk',
    'khmer': 'km',
    'kinyarwanda': 'rw',
    'konkani': 'gom',
    'korean': 'ko',
    'krio': 'kri',
    'kurdish kurmanji': 'ku',
    'kurdish sorani': 'ckb',
    'kyrgyz': 'ky',
    'lao': 'lo',
    'latin': 'la',
    'latvian': 'lv',
    'lingala': 'ln',
    'lithuanian': 'lt',
    'luganda': 'lg',
    'luxembourgish': 'lb',
    'macedonian': 'mk',
    'maithili': 'mai',
    'malagasy': 'mg',
    'malay': 'ms',
    'malayalam': 'ml',
    'maltese': 'mt',
    'maori': 'mi',
    'marathi': 'mr',
    'meiteilon manipuri': 'mni-Mtei',
    'mizo': 'lus',
    'mongolian': 'mn',
    'myanmar': 'my',
    'nepali': 'ne',
    'norwegian': 'no',
    'odia oriya': 'or',
    'oromo': 'om',
    'pashto': 'ps',
    'persian': 'fa',
    'polish': 'pl',
    'portuguese': 'pt',
    'punjabi': 'pa',
    'quechua': 'qu',
    'romanian': 'ro',
    'russian': 'ru',
    'samoan': 'sm',
    'sanskrit': 'sa',
    'scots gaelic': 'gd',
    'sepedi': 'nso',
    'serbian': 'sr',
    'sesotho': 'st',
    'shona': 'sn',
    'sindhi': 'sd',
    'sinhala': 'si',
    'slovak': 'sk',
    'slovenian': 'sl',
    'somali': 'so',
    'spanish': 'es',
    'sundanese': 'su',
    'swahili': 'sw',
    'swedish': 'sv',
    'tajik': 'tg',
    'tamil': 'ta',
    'tatar': 'tt',
    'telugu': 'te',
    'thai': 'th',
    'tigrinya': 'ti',
    'tsonga': 'ts',
    'turkish': 'tr',
    'turkmen': 'tk',
    'twi': 'ak',
    'ukrainian': 'uk',
    'urdu': 'ur',
    'uyghur': 'ug',
    'uzbek': 'uz',
    'vietnamese': 'vi',
    'welsh': 'cy',
    'xhosa': 'xh',
    'yiddish': 'yi',
    'yoruba': 'yo',
    'zulu': 'zu',
}

# Language code to language name mapping
LANGUAGE_NAMES = {v: k.capitalize() for k, v in LANGUAGE_CODES.items()}

class InvalidLanguageException(Exception):
    pass

def validate_language(language_name: str) -> str:
    normalized = language_name.strip().lower()
    if normalized not in LANGUAGE_CODES:
        raise InvalidLanguageException(
            f"Language '{language_name}' is not supported.\n"
            f"Supported languages:\n{', '.join(sorted(LANGUAGE_CODES.keys()))}"
        )
    return LANGUAGE_CODES[normalized]

def translate_to_multiple_languages(message: str, languages: list) -> str:
    result_lines = []
    for lang_code in languages:
        try:
            translated_text = GoogleTranslator(source='auto', target=lang_code).translate(text=message)
            language_name = LANGUAGE_NAMES.get(lang_code, lang_code)
            result_lines.append(f"{language_name}: {translated_text}")
        except Exception as e:
            result_lines.append(f"{lang_code}: Translation failed ({str(e)})")
    return "\n".join(result_lines)


